nodes:
    -  
        hostname: 192.168.1.1
        port: 5001
        id: 1
    -   
        hostname: 192.168.1.2
        port: 5002
        id: 2
    -   
        hostname: 192.168.1.3
        port: 5003
        id: 3
